server:
  port: 8762

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: discovery-server
  client:
    registerWithEureka: false    # ← Key: Don't register with itself
    fetchRegistry: false         # ← Key: Don't fetch from itself
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
